spring:
  application:
    name: project-platform

  datasource:
    url: jdbc:postgresql://localhost:5432/itch_clone
    username: postgres
    password: postgres

  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format-sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

